### PR TITLE
Mentions

### PR DESCRIPTION
**Pull request by sunyatax**

### CODE REVIEW

**Comment by sunyatax** [comment]
Ah, also forgot to mention we should reproduce this support for mentions across ShortForm, Photo, Audio, and Link as well. 

For Shortform, it's the entire text field. For Photo, Audio, and Link - only the caption. And then there's the Comment TextField as well.

Thanks @fayeed

**Comment by fayeed** [comment]
@sunyatax Yeah sure, first I will just complete the Longform & then move on to the others.

**Comment by sunyatax** [comment]
@fayeed how are we doin on this?

**Comment by fayeed** [comment]
Yeah going great

**Comment by fayeed** [comment]
Mentions for audio caption and post comments are only left

**Comment by sunyatax** [comment]
Awesome

**Comment by fayeed** [comment]
@sunyatax Can you take a look at this conflict?

**Comment by fayeed** [comment]
@sunyatax I think mentions are done I have found some bugs in the package itself, so I am going to look at it and fix those, we could later just update the package here to fix those.

**Comment by sunyatax** [comment]
@fayeed Can you specify what bugs you found in the package?

We're getting close - running into a few remaining things on this end...

### Bugs
1) Mentions aren't properly displayed when posting photos (either as original post or comments)

2) Trying to posting an expression or a comment **without** a mention returns a bad state. Looks like something is happening at mentionKey.currentState.controller.markUpText when there's no markup. This prevents the user from continuing on.

3) Empty query still returns the latest result. List should be empty if there's nothing after the @ symbol 
IMG_4480


### Improvements
1) Right now, we're automatically adding a mention if a user types the full username, even though they didn't click the name on the list. We should remove this features. Mentions should only be added when the user explicitly clicks on the list item.

2) You may already be planning on doing this, but we can clean up the code in a few places. For example, in the ParsedText widget we have a lot of duplicate code. We could simplify this into a custom mention parsed text widget that accepts normalTextStyle, matchTextStyle, and userProfile.

**Comment by fayeed** [comment]
@sunyatax I will take a look at bug 1, 2 & 3. As for the improvement number 1 that is by design because that's how Twitter handles it, I could maybe add a property it the package itself to disable this behavior.

Also yeah, I think creating a single widget for ParsedText would be good to eliminate some repeated code.

**Pull request merged**
