### PR TITLE
Polish signup

### LINKED ISSUE #931: Give some indication on sign up for reserved usernames (user Kickstarter email)

### LINKED ISSUE #946: Implement join community center on nav to center
Some ppl didn't get added because of some issues with sign up - this is a safeguard in that instance

### LINKED ISSUE #949: Enable posting to updates section in community center

### PR DESCRIPTION
**Pull request by sunyatax**
- Add disclaimer for crowdfunders to user email associated with crowdfunding account on sign up
- Build safeguard for people to join community groups if it fails on sign up
- Enable posting to updates in community center
- Polish server update text

Closes #946 
Closes #931 
Closes #949

### CODE REVIEW

**Comment by sunyatax** [comment]
@orestesgaolin would be good to chat if you have 15 min tomorrow. I'm having to clear my pubspec.lock + pod cache to run the simulator every time and these files change accordingly.

**Comment by sunyatax** [comment]
Closes #946 
Closes #931 
Closes #949

**Comment by orestesgaolin** [comment]
sure, let's call tomorrow; you seem to have serious issue with your Flutter installation

image

**Comment by sunyatax** [comment]
Not going to... let's see what's going on with my Flutter installation tmw.

**Pull request merged**
