### PR TITLE
Channels support

### PR DESCRIPTION
**Pull request by fayeed**
Channels support is completed just need to do some code cleanup & then it should be good to merge. @sunyatax can you take a look? also, I just copied the style for the mentions for the channels too, don't know if it needs to be styled differently or not, let me know I will update it by tommorrow.

### CODE REVIEW

**Comment by sunyatax** [comment]
Hey man, nicely done. A few things:

1. The server caps max channels at five. We are enforcing some limitations on the frontend when the user navigates to the screen where they can choose the context (Collective, Pack) and add channels manually. However, we should enforce it when the user types in channels through the '#' trigger. So, we should detect that if the channels list is already at 5 we don't add anymore or show the channels list whenever the user types '#'. 

2. Right now, tapping a channel on an open expression or comment triggers the getUser function. This should only be for mentions. Let's not call any function for now. In the near future, tapping a channel will filter the list but I want to rework some UI before we do that.

3. Tapping a channel on a single or two-column preview of an expression doesn't open the expression up. It should. I think this might be because there's another GestureDetector over the channel specifically so we should remove them for previews.

Everything else seems solid. Once this is done, feel free to start looking into RevenueCat. I'll be reworking the old channels UX.

**Comment by fayeed** [comment]
@sunyatax I was thinking we should just show a popup if the user has added more than five channels & is trying to navigating to the next screen.

**Comment by sunyatax** [comment]
Okay, I added the popup. Came across another thing while doing so...

It looks like we're letting people create empty channels. We should ignore adding/creating a channel if there is no text immediately after the hashtag. @fayeed

**Comment by sunyatax** [comment]
Did you also want to clean up the code? If so, I'll hold off on merging this PR.

**Comment by fayeed** [comment]
@sunyatax I will fix the empty channels issue you mentioned, and yeah was thinking of cleaning some repeated code.

**Comment by fayeed** [comment]
Hey @sunyatax, I think I am finished with the changes & should be good to merge, this PR also contains fixes for the emoji issue too.

**Pull request merged**
