### PR TITLE
Filter improvements

### PR DESCRIPTION
**Pull request by fayeed**
- [x]  When Filtering by channel, closing the panel, and reopening it, the list of open channels still appear. The feed should be empty after reopening & when the text field is blank
- [x]  Let's add a 'Reset Filters' option at the button that clears all the channels
- [x]  Let's expand the filter channel mechanism to work for group feeds as well, not just Collective

### CODE REVIEW

**Comment by tlalokyang** [comment]
@fayeed 

- Looks like we're no longer returning the list of popular channels when a user presses the TextField for filtering by Channels. Also, when I type something (i.e. heya) and then backspace, the channel results doesn't update. This is probably because we're not calling the api on an empty string.

**Comment by fayeed** [comment]
@sunyatax I thought that's what you meant, I can change that back. Also, do you mean that the channels should show up only when the text field is focused and the previous result should disappear once the panel is closed?

**Comment by fayeed** [comment]
@sunyatax made the changes.

**Comment by tlalokyang** [comment]
Yes exactly, cool!

**Pull request merged**
