### PR TITLE
Pinch to Photo zoom

### PR DESCRIPTION
**Pull request by fayeed**

### CODE REVIEW

**Comment by fayeed** [comment]
@sunyatax This PR should allow a zoomable Image viewer.

**Comment by sunyatax** [comment]
This is a good start. Few more things we should add:

1) When the photo is zoomed in/gesture detector activated, we should blur out the rest of the screen with a Colors.black.withOpacity(30). 

2) We should also allow people to keep the zoomed in state of the photo if they lift one finger off the app, and be able to move the photo around with one. Right now, people have to keep both fingers on the photo to keep it zoomed in or move around.

If you feel called, you're welcome to spin up an open source package for this! @fayeed

**Comment by fayeed** [comment]
@sunyatax I tried to replicate the behavior Instagram has so, they use two fingers for zooming and panning and as soon as you remove one finger it goes back, we could maybe try to handle it as Twitter handles it, have a separate screen. There is also a separate package for this called [photo_view](https://pub.dev/packages/photo_view) I haven't use this one for the current implementation as flutter had a built-in widget for this called `InteractiveView`, but its a little restrictive.

As for the backdrop, while the zooming is in play, I could do that, let me know your thoughts on that above.

**Comment by sunyatax** [comment]
Maybe we’re on different versions of Insta. For me, lifting one finger still allows me to stay zoomed and move the image around. This would be the desired result.

**Comment by fayeed** [comment]
@sunyatax I am using Insta on Android and it works with two fingers only, it could be a platform issue. Also, I think to remove one finger after a pinch gesture to pan just doesn't work great, at least for me personally I am accustomed to using two-finger for zooming & panning.

**Comment by sunyatax** [comment]
@fayeed  Okay, let's go ahead and ship this and revisit if we need to in the future.

**Comment by sunyatax** [comment]
gah, my b...

**Pull request merged**
