### PR TITLE
made url clickable

### PR DESCRIPTION
**Pull request by fayeed**

### CODE REVIEW

**Comment by sunyatax** [comment]
Looks like the url only catches text with the prefix https://www. - let's expand this to include www., http://, and https:// only prefixes as well

**Comment by fayeed** [comment]
@fayeed sure will fix this.

**Comment by fayeed** [comment]
@sunyatax I think we have an underline too for the URLs, what do you think?

**Comment by fayeed** [comment]
@sunyatax This should be good to merge now

**Comment by fayeed** [comment]
@sunyatax Can we merge this?

**Pull request merged**
